version: "3.8"

services:
  app:
    image: "node:14-slim"
    container_name: docker-nest-js
    build:
      context: .
      dockerfile: Dockerfile
      target: "testing"
    user: "node"
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - VERSION=1.0
    volumes:
      - .:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    tty: true
    command: sh -c "npm test || npm start"
    depends_on:
      - "postgrestest"
      - "postgres"


  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nft

  postgrestest:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nfttest