export const SEQUELIZE = 'SEQUELIZE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const TEAM_REPOSITORY = 'TEAM_REPOSITORY';
export const SECRET_KEY_ADMIN = 'SECRET_KEY_ADMIN';
export const SECRET_KEY_USER = 'SECRET_KEY_USER';