export const SEQUELIZE = 'SEQUELIZE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
export const TEAM_REPOSITORY = 'TEAM_REPOSITORY';
export const NFT_REPOSITORY = 'NFT_REPOSITORY';
export const SELLS_REPOSITORY = 'SELLS_REPOSITORY';
export const PASSWORD_LENGTH_GENERATED = 8;